"""Add search_queries table for analytics

Revision ID: 13468d1a1d01
Revises: 456cefb69a8f
Create Date: 2026-02-07 14:41:45.683304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13468d1a1d01'
down_revision: Union[str, Sequence[str], None] = '456cefb69a8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_queries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_queries_query'), ['query'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_queries_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_queries_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_queries_timestamp'))
        batch_op.drop_index(batch_op.f('ix_search_queries_site_id'))
        batch_op.drop_index(batch_op.f('ix_search_queries_query'))
        batch_op.drop_index(batch_op.f('ix_search_queries_id'))

    op.drop_table('search_queries')
    # ### end Alembic commands ###
